# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'SupTrackingV2' do
  pod 'Alamofire', '~> 4.7'
  

  # Pods for SupTrackingV2

  target 'SupTrackingV2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SupTrackingV2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
